version: "3.0"

services:
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    hostname: mysqldb
    ports:
      - 8080:8080
      - 3306:3306
    environment:
      - MYSQL_DATABASE=book-boss
      - MYSQL_ROOT_PASSWORD=password
