version: "3.0"

services:
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    hostname: mysqldb
    ports:
      - 8080:8080
      - 3306:3306
    environment:
      - MYSQL_DATABASE=book-boss
      - MYSQL_ROOT_PASSWORD=password

  api:
    build: .
    container_name: api
    hostname: api
    restart: always
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - mysqldb
    entrypoint: ./entrypoint.sh
